#!/usr/bin/env ruby

TOKEN = ENV["GITHUB_TOKEN"]
REPO = format("https://github.com/%s", ENV["GITHUB_REPOSITORY"])
BRANCH = ENV["GITHUB_REF"]
ACTOR = ENV["GITHUB_ACTOR"]

puts ACTOR

%x[git -c http.extraheader="AUTHORIZATION: Bearer #{TOKEN}" clone #{REPO} /tmp/x]
%x[cd /tmp/x/]
%x[git checkout #{BRANCH}"

puts %x[ls -la /tmp/x]

puts "% git --version"
puts %x[git --version]
puts "% pwd"
puts %x[pwd]
puts "% ls -la"
puts %x[ls -la]
puts "% git branch"
puts %x[git branch]
puts "% git branch -l"
puts %x[git branch -l]
puts "% git diff master..."
puts %x[git diff master...]

missing_specs =
  %x[git diff --diff-filter=AM --name-only master... -- 'app/**/*.rb']
    .split("\n")
    .map { _1.sub(/^app/, "spec") }
    .map { _1.sub(/\.rb$/, "_spec.rb") }
    .reject(&File.:exist?)
    .each { puts format("Missing spec file: %s", _1) }

exit(1) if missing_specs.any?
